Sunbird-inQuiry/inquiry-api-service

build/assessment-service/Jenkinsfile

Issue #SB-30221 feat: updated jenkins build script

---

.circleci/config.yml
assessment-api/assessment-actors/src/main/scala/org/sunbird/utils/BranchingUtil.scala
schemas/category/1.0/config.json
schemas/category/1.0/schema.json

Issue #SB-SB-30221 fix: updated script for circleci

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/managers/CopyManager.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/utils/BranchingUtil.scala

Issue #SB-30666 fix: Fixed Draft QuestionSet Copy Error

---

schemas/question/1.0/schema.json
schemas/questionset/1.0/schema.json

Issue #IQ-194 feat: added migrationVersion to schema

---

schemas/questionset/1.0/schema.json

Issue #IQ-149 fix: updated schema

---

scripts/jenkins-jobs/ArtifactUpload/Core/Assessment.xml
scripts/jenkins-jobs/ArtifactUpload/KnowledgePlatform/InquiryFlinkJob.xml
scripts/jenkins-jobs/Build/Core/Assessment.xml
scripts/jenkins-jobs/Build/KnowledgePlatform/InquiryFlinkJob.xml
scripts/jenkins-jobs/Deploy/Core/Assessment.xml
scripts/jenkins-jobs/Deploy/Core/InquiryUploadSchema.xml
scripts/jenkins-jobs/Deploy/KnowledgePlatform/InquiryFlinkJob.xml

Issue #IQ-193 feat: added jenkins job scripts

---

assessment-api/qs-hierarchy-manager/src/main/scala/org/sunbird/managers/HierarchyManager.scala

Issue #IQ-196 fix: added fix for live node addtion/deletion

---

assessment-api/qs-hierarchy-manager/src/main/scala/org/sunbird/managers/HierarchyManager.scala

Issue #IQ-213 fix: added fix for live node modification

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/utils/RequestUtil.scala

Issue #IQ-329 fix: corrected error messages

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/QuestionActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/QuestionSetActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/managers/AssessmentManager.scala
assessment-api/assessment-actors/src/test/resources/application.conf
assessment-api/assessment-actors/src/test/scala/org/sunbird/actors/QuestionActorTest.scala
assessment-api/assessment-actors/src/test/scala/org/sunbird/actors/QuestionSetActorTest.scala

Issue #IQ-300 feat: added validation in review api

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/QuestionActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/managers/AssessmentManager.scala
assessment-api/assessment-actors/src/test/scala/org/sunbird/actors/QuestionActorTest.scala

Issue #IQ-300 feat: added validation in question publish

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/managers/AssessmentManager.scala

Issue #IQ-300 fix: fix for question publish api

---

functional-tests/v1/env_question_questionset_v1.json
functional-tests/v1/ft_question_questionset_v1.json

Issue #IQ-258 feat: added functional test cases

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/managers/AssessmentV5Manager.scala
schemas/question/1.1/schema.json
schemas/questionset/1.1/config.json

Issue #IQ-385 fix: fixed question list  and questionset hierarchy api

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/managers/AssessmentV5Manager.scala

Issue #IQ-385 fix: fix for timeLimits

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/managers/AssessmentV5Manager.scala

Issue #IQ-385 fix: changes to populate outcomeDeclaration for SQ

---

.github/pull_request_template.md
README.md
assessment-api/assessment-actors/pom.xml
assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/ItemSetActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/managers/AssessmentManager.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/utils/RequestUtil.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/managers/AssessmentV5Manager.scala
assessment-api/assessment-actors/src/test/scala/org/sunbird/actors/QuestionActorTest.scala
assessment-api/assessment-actors/src/test/scala/org/sunbird/actors/QuestionSetActorTest.scala
assessment-api/pom.xml
assessment-api/qs-hierarchy-manager/pom.xml
assessment-api/qs-hierarchy-manager/src/main/scala/org/sunbird/managers/HierarchyManager.scala
assessment-api/qs-hierarchy-manager/src/main/scala/org/sunbird/managers/UpdateHierarchyManager.scala
assessment-api/qs-hierarchy-manager/src/test/scala/org/sunbird/managers/BaseSpec.scala
assessment-api/qs-hierarchy-manager/src/test/scala/org/sunbird/managers/HierarchyManagerTest.scala
assessment-api/qs-hierarchy-manager/src/test/scala/org/sunbird/managers/UpdateHierarchyManagerTest.scala
pom.xml

Issue IQ-543 feat: code changes for scala version upgrade

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/QuestionSetActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/managers/AssessmentManager.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionSetActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/managers/AssessmentV5Manager.scala
assessment-api/assessment-actors/src/test/resources/application.conf
assessment-api/assessment-actors/src/test/scala/org/sunbird/actors/QuestionSetActorTest.scala
assessment-api/assessment-actors/src/test/scala/org/sunbird/actors/v5/QuestionSetActorTest.scala
assessment-api/assessment-service/app/controllers/v4/QuestionSetController.scala
assessment-api/assessment-service/app/controllers/v5/QuestionSetController.scala
assessment-api/assessment-service/app/utils/ApiId.scala
assessment-api/assessment-service/app/utils/QuestionSetOperations.scala
assessment-api/assessment-service/conf/routes
assessment-api/assessment-service/test/controllers/v4/QuestionSetControllerSpec.scala
assessment-api/assessment-service/test/controllers/v5/QuestionSetControllerSpec.scala
schemas/questionset/1.0/config.json
schemas/questionset/1.1/config.json

@krgauraw
Design doc approved by DC - https://project-sunbird.atlassian.net/l/cp/HDuR6Nmz
Story - https://project-sunbird.atlassian.net/browse/IQ-125

IQ-125 Review flow for observation/survey

---

schemas/question/1.0/config.json
schemas/question/1.1/config.json
schemas/questionset/1.0/config.json
schemas/questionset/1.1/config.json

Issue #IQ-589 feat: added pii field config

---

schemas/question/1.0/schema.json
schemas/question/1.1/schema.json
schemas/questionset/1.0/schema.json
schemas/questionset/1.1/schema.json

Issue #IQ-589 feat: added creator prop in schema

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/managers/AssessmentV5Manager.scala

Issue #IQ-664 fix: added new value of compatibilityLevel

---

schemas/question/1.0/config.json
schemas/question/1.1/config.json
schemas/questionset/1.0/config.json
schemas/questionset/1.1/config.json

Issue #IQ-677 fix: added author as pii field

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionSetActor.scala

Issue #IQ-371 fix: fix for get hierarchy api

---

scripts/cassandra-db/cassandra.cql

Issue #IQ-729 feat: added cassandra db script

---

scripts/cassandra-db/cassandra.cql

Issue #IQ-729 feat: added cassandra script

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/QuestionActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/QuestionSetActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/managers/AssessmentManager.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionSetActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/managers/AssessmentV5Manager.scala
assessment-api/assessment-service/app/controllers/BaseController.scala
assessment-api/assessment-service/app/controllers/v4/QuestionController.scala
assessment-api/assessment-service/app/controllers/v4/QuestionSetController.scala
assessment-api/assessment-service/app/controllers/v5/BaseController.scala
assessment-api/assessment-service/app/controllers/v5/QuestionController.scala
assessment-api/assessment-service/app/controllers/v5/QuestionSetController.scala
assessment-api/assessment-service/app/filters/AccessLogFilter.scala

Issue #IQ-744 feat: code changes for entry exit log for publish api

---

schemas/question/1.0/config.json
schemas/question/1.1/config.json
schemas/questionset/1.0/config.json
schemas/questionset/1.1/config.json
test_schema/question/1.0/config.json
test_schema/question/1.1/config.json
test_schema/questionset/1.0/config.json
test_schema/questionset/1.1/config.json

Issue #IQ-756 fix: removed author from pii config

---

assessment-api/assessment-service/app/controllers/BaseController.scala
assessment-api/assessment-service/app/controllers/v4/QuestionController.scala
assessment-api/assessment-service/app/controllers/v4/QuestionSetController.scala
assessment-api/assessment-service/app/controllers/v5/BaseController.scala
assessment-api/assessment-service/app/controllers/v5/QuestionController.scala
assessment-api/assessment-service/app/controllers/v5/QuestionSetController.scala

Issue #IQ-751 fix: added featureId cdata

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionSetActor.scala
assessment-api/qs-hierarchy-manager/src/main/scala/org/sunbird/managers/UpdateHierarchyManager.scala

Issue #IQ-379 fix: added prevStatus

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/QuestionActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/QuestionSetActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/managers/AssessmentManager.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionSetActor.scala
assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/managers/AssessmentV5Manager.scala
assessment-api/assessment-service/app/controllers/BaseController.scala
assessment-api/assessment-service/app/controllers/v4/QuestionController.scala
assessment-api/assessment-service/app/controllers/v4/QuestionSetController.scala
assessment-api/assessment-service/app/controllers/v5/BaseController.scala
assessment-api/assessment-service/app/controllers/v5/QuestionController.scala
assessment-api/assessment-service/app/controllers/v5/QuestionSetController.scala

Issue #IQ-793 fix: added code for X-Feature-Name

---

functional-tests/v2/env_question_questionset_v2.json

Issue #IQ-803 fix: added variables for v2 api

---

assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionSetActor.scala
assessment-api/assessment-service/app/controllers/v5/QuestionSetController.scala
schemas/questionset/1.1/config.json

Issue #IQ-805 fix: updated code for questionset update api.
